import { ReactNode } from 'react';
import StreamVideoProvider from '../../../Provider/StreamClientProvider';
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:"/icon/zoomlogo.png"
};


const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <main>
      <StreamVideoProvider>{children}</StreamVideoProvider>
      <ToastContainer/>
    </main>
  );
};

export default RootLayout;