
import Mobilenav from '@/components/Mobilenav'
import Navbar from '@/components/Navbar'
import Sidebarlinks from '@/components/sidebarlinks'
// import Sidebarlinks from '@/components/sidebarlinks'
import React from 'react'
import { ToastContainer } from 'react-toastify'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:"/icon/zoomlogo.png"
};

const Layout = ({children}:{children:React.ReactNode}) => {
  return (<>
  <div className='hidden  md:flex'> 
<Navbar/>
  </div>
  <div className='md:hidden'>
        <Mobilenav/>
  </div>

      <div className='flex '>
        
       <div className='hidden md:block'>
       <Sidebarlinks/>
       </div>
      <div className='p-2 w-full '> 
   
       {children}
        </div>  
    
    
    </div>
       <ToastContainer/>
  </>
  )
}

export default Layout